version: "3.8"

services:
  # Service Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: simbah-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - simbah-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Service Aplikasi Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simbah-api
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - simbah-network
    volumes:
      - ./logs:/usr/src/app/logs
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  simbah-network:
    driver: bridge
